CAO-20317 Decrotive Images
LivePersonInc/json-pollock pull request #52
Opened 2021-03-30 18:38 UTC by RJGrunau

This PR fixes an issue where carousel images were given misleading attributes. Reference internal Jira ticket [CAO-20317](https://jira.liveperson.com/browse/CAO-20317)

2021-03-31 19:08 UTC, meirotstein commented
@RJGrunau this PR eliminates the impact of the `alt` configuration (alt attribute) and the `tooltip` configuration (aria-label and title). see doc:
https://developers.liveperson.com/getting-started-with-rich-messaging-introduction.html

While adding the Presentation role makes sense, I don't really understand why to remove the other attributes - as these are only configurations. if some brand having issues with these attributes then the right approach would be not to use these configurations on the SC json.

An example for JSON which are not using these configurations:
https://livepersoninc.github.io/json-pollock/editor/?gist=882108ce170ec6f30adc2285a042d76d

WDYT?

2021-03-31 22:53 UTC, RJGrunau commented
@meirotstein Sorry. I was using a hammer when I should have been using a more exact tool. I updated this to look if a tooltip is provided, if not, give the image a role of presentation.

2021-04-01 06:47 UTC, meirotstein requested changes
Thanks @RJGrunau ! just additional small comment

2021-04-02 12:46 UTC, meirotstein approved these changes

2021-04-06 17:27 UTC, merged